# Generated by Django 5.2 on 2025-04-12 04:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodation_images/')),
                ('type', models.CharField(default='', max_length=100)),
                ('owner_info', models.TextField(default='')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('distance', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_beds', models.IntegerField(default=0)),
                ('number_of_bedrooms', models.IntegerField(default=0)),
                ('availability_start', models.DateField(default=datetime.date.today)),
                ('availability_end', models.DateField(default=datetime.date.today)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CedarsSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('degree_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('accommodation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.accommodation')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.student')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('contract_status', models.CharField(default='draft', max_length=50)),
                ('reservation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('accommodation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.accommodation')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='')),
                ('is_read', models.BooleanField(default=False)),
                ('cedars_specialist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.cedarsspecialist')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.user')),
            ],
        ),
    ]
