# Generated by Django 5.1.7 on 2025-04-11 09:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='availability_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='availability_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images/'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='number_of_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='number_of_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='owner_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='property_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='cedars_specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.cedarsspecialist'),
        ),
        migrations.AddField(
            model_name='rating',
            name='accommodation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.accommodation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.student'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cedarsspecialist',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.student'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='accommodation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.accommodation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('contract_status', models.CharField(default='draft', max_length=50)),
                ('reservation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.user'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.user'),
        ),
    ]
