# Generated by Django 5.1.7 on 2025-04-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
    ]
