# Generated by Django 5.2 on 2025-04-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="accommodation_system.accommodation",
                unique=True,
            ),
        ),
    ]
