# Generated by Django 5.1.7 on 2025-04-11 13:27
'''
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0002_user_remove_accommodation_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='distance',
        ),
    ]
'''
