# Generated by Django 5.2 on 2025-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accommodation_system",
            "0002_alter_cedarsspecialist_cedars_specialist_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="id",
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("signed", "Signed"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
