# Generated by Django 5.1.7 on 2025-04-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0002_accommodation_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='student',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accommodation_system.accommodation'),
        ),
    ]
