# Generated by Django 5.1.7 on 2025-04-15 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0003_remove_reservation_status_remove_reservation_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rating_photos/'),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('cancelled', 'Cancelled')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accommodation_system.student'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.accommodation'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation_system.student'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('student', 'accommodation')},
        ),
    ]
