# Generated by Django 5.1.7 on 2025-04-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0004_rating_comment_rating_created_at_rating_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='student',
            new_name='student_id',
        ),
    ]
