# Generated by Django 5.1.7 on 2025-04-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0005_rename_student_reservation_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='student_id',
            new_name='student',
        ),
    ]
