# Generated by Django 5.1.7 on 2025-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0006_rename_student_id_reservation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
