# Generated by Django 5.1.7 on 2025-04-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0007_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
