# Generated by Django 5.1.7 on 2025-04-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_system', '0009_remove_notification_user_notification_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_id',
        ),
    ]
