# Generated by Django 5.1.7 on 2025-04-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('unsigned', 'unsigned'), ('signed', 'Signed'), ('failed', 'Failed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hku.reservation'),
        ),
    ]
