# Generated by Django 5.1.7 on 2025-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
