# Generated by Django 5.1.7 on 2025-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhk', '0002_alter_contract_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='property_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
