# Generated by Django 5.1.7 on 2025-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhk', '0003_accommodation_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='degree_type',
            new_name='university',
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
