# Generated by Django 5.1.7 on 2025-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhk', '0009_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
