# Generated by Django 5.1.7 on 2025-05-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuhk', '0010_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
