# Generated by Django 5.1.7 on 2025-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhk', '0013_remove_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rating_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
