openapi: 3.0.3
info:
  title: UniHaven API
  version: 1.0.0
  description: API for managing accommodations and reservations.

tags:
   - name: accommodations
     description: Manage accommodation listings, uploads, and search operations.
   - name: reservations
     description: Handle booking creation, cancellation, and retrieval.
   - name: students
     description: Manage student profiles and creation.
   - name: cedars_specialists
     description: Manage Cedars Specialists and their details.

paths:
  /accommodations/:
    get:
      summary: Lists the accommodations
      operationId: accommodations_list
      tags:
      - accommodations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Accommodation'
          description: ''
  /accommodations/rate/:
    post:
      summary: Rates the accommodations
      operationId: accommodations_rate_create
      tags:
      - accommodations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rating'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Rating'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Rating'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
          description: ''
  /accommodations/search/:
    get:
      summary: Apply filters to accommodation searches
      operationId: accommodations_search_list
      parameters:
      - in: query
        name: available_from
        schema:
          type: string
          format: date
        description: Available From (YYYY-MM-DD)
      - in: query
        name: available_to
        schema:
          type: string
          format: date
        description: Available To (YYYY-MM-DD)
      - in: query
        name: campus
        schema:
          type: string
        description: Distance To HKU Campus (Ascending Order)
      - in: query
        name: max_price
        schema:
          type: number
      - in: query
        name: min_price
        schema:
          type: number
      - in: query
        name: number_of_bedrooms
        schema:
          type: integer
      - in: query
        name: number_of_beds
        schema:
          type: integer
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: type
        schema:
          type: string
      tags:
      - accommodations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Accommodation'
          description: ''
  /accommodations/search/{name}/:
    get:
      summary: Searches the accommodation with the included name
      operationId: accommodations_search_retrieve
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - accommodations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accommodation'
          description: ''
  /accommodations/upload/:
    get:
      summary: Uploads a new accommodation listing
      operationId: accommodations_upload_list
      tags:
      - accommodations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Accommodation'
          description: ''
    post:
      summary: Views details of newly uploaded accommodation
      operationId: accommodations_upload_create
      tags:
      - accommodations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Accommodation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Accommodation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Accommodation'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accommodation'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /cedars_specialists/:
    get:
      summary: Views Cedar Specialists instances
      operationId: cedars_specialists_list
      tags:
      - cedars_specialists
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CedarsSpecialist'
          description: ''
  /cedars_specialists/create/:
    post:
      summary: Creates Cedars Specialist profile
      operationId: cedars_specialists_create_create
      tags:
      - cedars_specialists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CedarsSpecialist'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CedarsSpecialist'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CedarsSpecialist'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CedarsSpecialist'
          description: ''
  /reservations/:
    get:
      summary: Lists the current reservations
      operationId: reservations_list
      parameters:
      - in: query
        name: status
        schema:
          type: string
          enum:
          - available
          - cancelled
          - reserved
        description: |-
          * `available` - Available
          * `reserved` - Reserved
          * `cancelled` - Cancelled
      - in: query
        name: student
        schema:
          type: integer
      tags:
      - reservations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
          description: ''
  /reservations/{reservation_id}/:
    get:
      summary: View the reservation with the included reservation ID
      operationId: reservations_retrieve
      parameters:
      - in: path
        name: reservation_id
        schema:
          type: string
        required: true
      tags:
      - reservations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
          description: ''
    put:
      operationId: reservations_update
      parameters:
      - in: path
        name: reservation_id
        schema:
          type: string
        required: true
      tags:
      - reservations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Reservation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Reservation'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
          description: ''
    delete:
      operationId: reservations_destroy
      parameters:
      - in: path
        name: reservation_id
        schema:
          type: string
        required: true
      tags:
      - reservations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /reservations/{reservation_id}/cancel/:
    delete:
      summary: Cancels the reservation with the included reservation ID
      operationId: reservations_cancel_destroy
      parameters:
      - in: path
        name: reservation_id
        schema:
          type: string
        required: true
      tags:
      - reservations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /reservations/create/:
    post:
      summary: Makes reservation of an accommodation
      operationId: reservations_create_create
      tags:
      - reservations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Reservation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Reservation'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
          description: ''
  /students/create/:
    post:
      summary: Creates student profile
      operationId: students_create_create
      tags:
      - students
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
components:
  schemas:
    Accommodation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        image:
          type: string
          format: uri
          nullable: true
        type:
          type: string
          maxLength: 100
        owner_info:
          type: string
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        area:
          type: string
          maxLength: 100
        distance: {}
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        number_of_beds:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        number_of_bedrooms:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        availability_start:
          type: string
          format: date
        availability_end:
          type: string
          format: date
        create_date:
          type: string
          format: date-time
          readOnly: true
        status:
          $ref: '#/components/schemas/AccommodationStatusEnum'
      required:
      - create_date
      - id
    AccommodationStatusEnum:
      enum:
      - available
      - reserved
      type: string
      description: |-
        * `available` - Available
        * `reserved` - Reserved
    CedarsSpecialist:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 254
        cedars_specialist_id:
          type: integer
          readOnly: true
      required:
      - cedars_specialist_id
      - email
    PatchedReservation:
      type: object
      properties:
        student_id:
          type: integer
          writeOnly: true
        accommodation:
          type: integer
          writeOnly: true
        status:
          allOf:
          - $ref: '#/components/schemas/ReservationStatusEnum'
          readOnly: true
        accommodation_name:
          type: string
          readOnly: true
    Rating:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        score:
          type: integer
          maximum: 5
          minimum: 1
        comment:
          type: string
          nullable: true
        photo:
          type: string
          format: uri
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        student:
          type: integer
          readOnly: true
        accommodation:
          type: integer
          readOnly: true
      required:
      - accommodation
      - created_at
      - id
      - score
      - student
      - updated_at
    Reservation:
      type: object
      properties:
        student_id:
          type: integer
          writeOnly: true
        accommodation:
          type: integer
          writeOnly: true
        status:
          allOf:
          - $ref: '#/components/schemas/ReservationStatusEnum'
          readOnly: true
        accommodation_name:
          type: string
          readOnly: true
      required:
      - accommodation
      - accommodation_name
      - status
      - student_id
    ReservationStatusEnum:
      enum:
      - available
      - reserved
      - cancelled
      type: string
      description: |-
        * `available` - Available
        * `reserved` - Reserved
        * `cancelled` - Cancelled
    Student:
      type: object
      properties:
        student_id:
          type: string
          maxLength: 255
        name:
          type: string
          maxLength: 255
        degree_type:
          type: string
          maxLength: 100
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
