# Generated by Django 5.2 on 2025-04-26 14:35

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CedarsSpecialist',
            fields=[
                ('cedars_specialist_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('degree_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(default='', max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodation_images/')),
                ('type', models.CharField(default='', max_length=100)),
                ('area', models.CharField(default='', max_length=100)),
                ('owner_info', models.TextField(default='')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('distance', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_beds', models.IntegerField(default=0)),
                ('number_of_bedrooms', models.IntegerField(default=0)),
                ('availability_start', models.DateField(default=datetime.date.today)),
                ('availability_end', models.DateField(default=datetime.date.today)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='available', max_length=50)),
                ('room_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('flat_number', models.CharField(default='', max_length=50)),
                ('floor_number', models.CharField(default='', max_length=50)),
                ('geo_address', models.TextField(default='')),
            ],
            options={
                'unique_together': {('room_number', 'flat_number', 'floor_number', 'geo_address')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('cancelled', 'Cancelled')], default='available', max_length=50)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hkust.accommodation', unique=True)),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hkust.student')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('contract_status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('reservation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hkust.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rating_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_ratings', to='hkust.accommodation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='hkust.student')),
            ],
        ),
    ]
