# Generated by Django 5.1.7 on 2025-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkust', '0002_accommodation_num_ratings_accommodation_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='property_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
