# Generated by Django 5.1.7 on 2025-05-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkust', '0006_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
